# Site settings 配置站点
title: 'LaingKe'
description: 'LaingKe 的博客'
keywords: '个人博客'
url: 'https://laingke.github.io' # your host

# nav 中文字符空格：&emsp;
nav: # 最佳体验 六个标签 且最好每个标签不超过4中文字
  首页: '/'
  标签: '/tags.html'
  时间线: '/timeline.html'
#  我的简历: '/resume.html'
  关于博主: '/about.html'
  友情链接: '/friendLink.html'

# 博主
author: true
name: '梁科'
nickName: 'LaingKe'
webtitle: 'LaingKe 的博客'
bio: '码农一枚'
about: true
aboutyou: '<p style="text-align: center;">爱生活、爱艺术、爱音乐、爱设计、爱编程。</p>'
portraits: '/assets/profile.png' # your portraits image file path

# SNS
SNS: true
SNS-icon: #['Facebook', 'weibo', 'qq', 'github', 'Dribbble', 'Twitter', 'instagram', 'weixin', 'Codepen']
  mail: 'mailto:liangkexxxxx@gmail.com'
  weixin: '/assets/profile_wx.jpg' # 你的微信二维码存放的地址
  qq: 'https://wpa.qq.com/msgrd?v=3&uin=1793469032&site=qq&menu=yes' # 你的qq二维码存放的地址 or http://wpa.qq.com/msgrd?v=3&uin='你的QQ号'&site=qq&menu=yes
  github: 'https://github.com/laingke'
  # Codepen: ''
  # weibo: ''
  # instagram: ''
  # Twitter: ''
  # Dribbble: ''
  # Facebook: ''
  # Google: ''
  # zhihu: ''
  # juejin: ''
  # twitch: ''

# 分页
paginate: 2
paginatepath: ['page:num']

# since
footer:
  since: 2017

# Markdown
markdown: kramdown
kramdown:
  input: GFM
# 代码高亮 使用rouge
highlighter: rouge
# 代码高亮主题使用pygments主题: autumn\ default\ emacs\ friendly\ manni\ murphy\ pastie\ perldoc\ tango 任选一个你喜欢的主题名称填在下面的单引号中
pygmentsTheme: 'default'

# 友情链接
friends:
  jekyll: 'https://www.jekyll.com.cn/'

# 评论 最佳体验 在disqus、livere和Gitment之间三选一
# disqus 评论
disqus: false
disqus_url: '' # https://abc.disqus.com/embed.js
# 来必力评论
livere: false
livere_uid: '' # MTAyMC8zNDI2OS8xMDgwNg==
# Gitment评论 OAuth Application
Gitment: true
Gitment_owner: 'laingke'  # github用户名
Gitment_repo: 'laingke.github.io'  # github博客存放的仓库名
client_id: '48244eb8b375a7ad5f38'  # 注册 OAuth Application 后获得的 client_id
client_secret: 'a95cc1ee409623bcc088a7f1f9005ddf9d5c5795'  # 注册 OAuth Application 后获得的 client_secret

# Share : weibo, qq, wechat, tencent, douban, qzone, linkedin, diandian, facebook, twitter, google
social-share: true
social-share-items: ['qq', 'wechat', 'weibo', 'twitter', 'facebook']

# 百度统计 在baidu-url里填写自己相关的url代码
baidu: false
baidu-url: ''
# 谷歌分析 在google-ID里填写自己在谷歌分析获得的追踪ID
google: false
google-ID: ''

# 博客头信息备选颜色（该部分在站点中不充当站点变量，将其写在post的头信息中用来充当页面变量）
color: rgb(154,133,255) rgb(255,90,90) rgb(255,210,32) rgb(98,170,255)

# 简历设置
resume:
  workHistory:
    - work1:
      company: <a href="http://www.inspur.com">浪潮集团有限公司</a>数字媒体事业部 | Digital Media Business Unit Of Inspur Group Co.,Ltd.
      location: 深圳，中国
      title: Java 研发工程师
      started: 2017.7
      duration: (2017.7 - 现在)
      description: 从事后台 / 后端研发工作，具有团队协作以及独立工作经验，主手 Java，熟悉 PHP, Ruby 等编程语言以及相关框架且具有相关开发工作经验，负责软件开发周期中的设计，开发，测试，部署，支持等工作。
  educationHistory:
    - education1:
      organization: <a href="https://www.sdu.edu.cn">山东大学</a> | Shandong University
      location: 济南，山东，中国
      degree: 学士学位
      major: 计算机科学与技术专业
      started: 2013
      duration: (2013 - 2017)
      description: 毕业于山东大学计算机科学与技术专业
  languages:
    - language1:
      name: 汉语
      proficiency: Native
    - language2:
      name: 英语
      proficiency: CET 6
    - language3:
      name: 日语
      proficiency: Limit
  programmingSkills:
    - skill1:
      name: Java / Java EE / Spring Framework
      percentage: 85%
    - skill2:
      name: HTML / CSS / JS
      percentage: 84%
    - skill3:
      name: Linux
      percentage: 80%
    - skill4:
      name: Ruby / Ruby on Rails
      percentage: 70%
    - skill5:
      name: PHP
      percentage: 60%
    - skill6:
      name: Database
      percentage: 75%
